name = "BoxLeastSquares"
uuid = "6c353534-c22b-44cc-9076-7b904de9fadc"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.2.0-dev"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
RecipesBase = "1"
julia = "1.6"
