name = "BoxLeastSquares"
uuid = "6c353534-c22b-44cc-9076-7b904de9fadc"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.3"
